# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User:
        #Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        #AppBundle\Entity\User: 
        #Symfony\Component\Security\Core\User\User:  
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        mysql:
            entity:
                class: AppBundle:User
                property: username
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    #providers:
    #    in_memory:
    #        memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            provider: mysql
            form_login: 
                always_use_default_target_path: true
                default_target_path: /
                failure_path: login_failure
                login_path: login
                check_path: login
                target_path_parameter: redirect_url
                use_forward: false
            logout:
                path:   /logout
                invalidate_session: false
                target: /
                delete_cookies:
                    a: { path: null, domain: null }
                    b: { path: null, domain: null }
    access_control:
    # require ROLE_ADMIN for /admin*     
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/index, roles: IS_AUTHENTICATED_ANONYMOUSLY }    
        - { path: ^/product, roles: ROLE_USER}
        - { path: ^/profile, roles: ROLE_USER}
        - { path: ^/advertise, roles: ROLE_USER}   
        - { path: ^/aboutus, roles: IS_AUTHENTICATED_ANONYMOUSLY}
