_dashboard:
    path: /agroov
    defaults: { _controller: AppBundle:Agroov:index}

_upload_arecord_image:
    path: /upload
    defaults: { _controller: AppBundle:Arecord:upload}

_about_us:
    path: /aboutus
    defaults: { _controller: AppBundle:Cmpy:aboutus}

_rules:
    path: /rules
    defaults: { _controller: AppBundle:Cmpy:rules}

_save_arecord:
    path: /save
    defaults: { _controller: AppBundle:Arecord:save}

_user_registration:
    path: /user/registration
    defaults: { _controller: AppBundle:User:registration}

_upload_user_image:
    path: /registration/upload
    defaults: { _controller: AppBundle:User:upload}

logincheck:
    path:  /logincheck
    defaults: { _controller: AppBundle:Security:logincheck }

login:
    path:  /login
    defaults: { _controller: AppBundle:Security:login }

logout:
    path:  /logout
    defaults: { _controller: AppBundle:User:logout }

login_failure:
    path : /forgot_password
    defaults: { _controller: AppBundle:Security:forgotpassword }

_send_password:
    path : /send_password
    defaults: { _controller: AppBundle:Security:sendpassword }

_profile_index:
    path: /profile
    defaults: {_controller: AppBundle:User:profile }

_adverts:
    path: /adverts
    defaults: {_controller: AppBundle:Advert:index }

advertise:
    path: /advertise
    defaults: {_controller: AppBundle:Advert:add }

_upload_advert_image:
    path: /advert/upload
    defaults: { _controller: AppBundle:Advert:upload }

_advert_view:
    path: /advert/view/{url}
    defaults: { _controller: AppBundle:Advert:view }

_advert_edit:
    path: /advert/edit/{id}
    defaults: { _controller: AppBundle:Advert:edit }

_advert_delete:
    path: /advert/delete/{id}
    defaults: { _controller: AppBundle:Advert:delete }

_delete_advert_image:
    path: /user/delete_image
    defaults: {_controller: AppBundle:Advert:deleteImage}

_get_category_for_user:
    path: /user_view_category
    defaults: {_controller: AppBundle:Category:index}

_delete_user_image:
    path: /user/delete_image
    defaults: {_controller: AppBundle:User:deleteImage}
_add_forum : 
    path : /forum/add
    defaults : {_controller: AppBundle:Forum:add}

_forum : 
    path : /forum
    defaults : {_controller: AppBundle:Forum:index}

_publication : 
    path : /publication
    defaults : {_controller: AppBundle:Publication:index}

_publication_view:
    path: /publication/view/{url}
    defaults: {_controller: AppBundle:Publication:view}

_new_post:
    path: /publication/add
    defaults: {_controller: AppBundle:Publication:add}

_upload_publication_image:
    path: /publication/upload
    defaults: {_controller: AppBundle:Publication:upload}

_top_banner : 
    path : /topbanner
    defaults : {_controller: AppBundle:Cmpy:topbanner}

_left_banner : 
    path : /leftbanner
    defaults : {_controller: AppBundle:Cmpy:leftbanner}


_fmessage_history:
    path : /forum/history/{forum_id}
    defaults: {_controller: AppBundle:Forum:history}

_logo_path:
    path : /logo
    defaults: {_controller: AppBundle:Cmpy:logo}

_country:
    path : /country
    defaults: {_controller: AppBundle:Country:index}

_currency:
    path : /currency
    defaults: {_controller: AppBundle:Currency:index}

_region:
    path: /region/{country_id}
    defaults: {_controller: AppBundle:Region:index}

_city:
    path: /city/{region_id}
    defaults: {_controller: AppBundle:City:index}

_sale_category:
    path: /sale/{category_id}
    defaults: {_controller: AppBundle:Default:sale}

_buy_category:
    path: /buy/{category_id}
    defaults: {_controller: AppBundle:Default:buy}

_service_category:
    path: /service/{category_id}
    defaults: {_controller: AppBundle:Default:service}

_vacancy_category:
    path: /vacancy/{category_id}
    defaults: {_controller: AppBundle:Default:vacancy}

_rent_category:
    path: /rent/{category_id}
    defaults: {_controller: AppBundle:Default:rent}

_charity:
    path : /charity
    defaults: {_controller:AppBundle:Charity:index}

_company:
    path : /shops
    defaults: {_controller:AppBundle:Company:index}

_company_view:
    path : /{url}
    defaults: {_controller:AppBundle:Company:view}

_add_company:
    path : /shop/add
    defaults: {_controller:AppBundle:Company:add}

_company_map:
    path : shop/map
    defaults: {_controller:AppBundle:Company:map}

_reklam:
    path: /reklam
    defaults: {_controller:AppBundle:Reklam:index}

_admin:
    path: /admin
    defaults: {_controller:AppBundle:Admin:index}

_admin_topbanner:
    path: /admin/topbanner
    defaults: {_controller:AppBundle:Admin:topbanner}

_admin_addtopbanner:
    path: /admin/addtopbanner
    defaults: {_controller:AppBundle:Admin:addtopbanner}

_admin_topbanner_delete:
    path: /admin/topbannerdelete/{image}/{id}
    defaults: {_controller:AppBundle:Admin:topbannerdelete}

_admin_leftbanner:
    path: /admin/leftbanner
    defaults: {_controller:AppBundle:Admin:leftbanner}

_admin_addleftbanner:
    path: /admin/addleftbanner
    defaults: {_controller:AppBundle:Admin:addleftbanner}

_admin_leftbanner_delete:
    path: /admin/leftbannerdelete/{image}/{id}
    defaults: {_controller:AppBundle:Admin:leftbannerdelete}

_admin_layer:
    path: /admin/layer
    defaults: {_controller:AppBundle:Layer:index}

_admin_layer_delete:
    path: /admin/layerdelete/{image}/{id}
    defaults: {_controller:AppBundle:Layer:delete}

_admin_addlayer:
    path: /admin/addlayer
    defaults: {_controller:AppBundle:Layer:add}

_user_company:
    path: /company/usercompany
    defaults: {_controller:AppBundle:Company:usercompany}

_recovery:
    path: /recovery/{token}
    defaults: {_controller:AppBundle:Security:recovery}

_new_password:
    path: /newpassword/{token}
    defaults: {_controller:AppBundle:Security:newpassword}

_map:
    path: /shops/map
    defaults: {_controller:AppBundle:Map:index}
_layer:
    path : /layer/layers
    defaults: {_controller:AppBundle:Layer:layers}


